[all:vars]
ansible_user=vagrant
[nginx]
nginx-rp ansible_host=10.77.133.2
[n8n_web]
n8n-web ansible_host=10.77.133.3
[n8n_worker]
n8n-worker ansible_host=10.77.133.4
[redis]
redis ansible_host=10.77.133.5
[postgres]
postgresql ansible_host=10.77.133.6
[wikijs]
wikijs ansible_host=10.77.133.7
[ollama]
ollama ansible_host=10.77.133.8