# -*- mode: ruby -*-
# vi: set ft=ruby :
# Stack:
# - nginx reverse proxy
# - n8n web
# - n8n worker
# - Redis
# - PostgreSQL
# - Wiki.js
# - Ollama
#
# Provider:
# - VirtualBox
#
# Provisioning:
# - Ansible (будет добавлен позже)
#
# Network:
# - isolated private subnet

# Base Ubuntu image
VAGRANT_BOX = "ubuntu/jammy64"
# Internal private subnet
NETWORK_PREFIX = "10.77.133"
# /28 subnet = 16 addresses
NETMASK = "255.255.255.240"
# VM boot timeout
BOOT_TIMEOUT = 600
# Prefix для VM names в VirtualBox
PROJECT_NAME = "260227"
# VM FACTORY
def create_vm(config, params)
  config.vm.define params[:name] do |vm|
    # Ubuntu box
    vm.vm.box = VAGRANT_BOX
    # Hostname внутри VM
    vm.vm.hostname = params[:hostname]
    # Максимальное ожидание boot
    vm.vm.boot_timeout = BOOT_TIMEOUT
    # Private network
    vm.vm.network "private_network",
      ip: "#{NETWORK_PREFIX}.#{params[:ip]}",
      netmask: NETMASK
    # Optional public network
    if params[:public_network]
      vm.vm.network "public_network"
    end
    # Монтируем локальную папку внутрь VM
    if params[:shared_folder]
      vm.vm.synced_folder(
        "./#{params[:shared_folder]}",
        "/home/vagrant/#{params[:shared_folder]}"
      )
    end
    vm.vm.provider "virtualbox" do |vb|
      # VM name внутри VirtualBox
      vb.name = "#{PROJECT_NAME}-#{params[:name]}"
      # RAM
      vb.memory = params[:memory]
      # CPU
      vb.cpus = params[:cpus]
    end
  end
end
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # NGINX REVERSE PROXY
  create_vm(config,
    name: "nginx-rp",
    hostname: "nginx-rp",
    ip: 2,
    memory: 1024,
    cpus: 1,
    shared_folder: "nginx",
    public_network: false
  )
  # N8N WEB
  create_vm(config,
    name: "n8n-web",
    hostname: "n8n-web",
    ip: 3,
    memory: 1024,
    cpus: 1,
    shared_folder: "n8n-web",
    public_network: false
  )
  # N8N Worker
  create_vm(config,
    name: "n8n-worker",
    hostname: "n8n-worker",
    ip: 4,
    memory: 2048,
    cpus: 1,
    shared_folder: "n8n-worker",
    public_network: false
  )
  # REDIS
  create_vm(config,
    name: "redis",
    hostname: "redis",
    ip: 5,
    memory: 1024,
    cpus: 1,
    public_network: false
  )
  # POSTGRESQL

  create_vm(config,
    name: "postgresql",
    hostname: "postgresql",
    ip: 6,
    memory: 2048,
    cpus: 1,
    public_network: false
  )
  # WIKI.JS
  create_vm(config,
    name: "wikijs",
    hostname: "wikijs",
    ip: 7,
    memory: 2048,
    cpus: 1,
    shared_folder: "wikijs",
    public_network: false
  )
  # OLLAMA
  create_vm(config,
    name: "ollama",
    hostname: "ollama",
    ip: 8,
    memory: 6192,
    cpus: 1,
    shared_folder: "ollama",
    public_network: false
  )
end